// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarRefreshToken = `-- name: BuscarRefreshToken :one
SELECT id, user_id, token_hash, expira_em, revogado, criado_em FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) BuscarRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, buscarRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiraEm,
		&i.Revogado,
		&i.CriadoEm,
	)
	return i, err
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id, email, senha_hash, criado_em FROM users
WHERE email = $1
`

func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenhaHash,
		&i.CriadoEm,
	)
	return i, err
}

const buscarUsuarioPorID = `-- name: BuscarUsuarioPorID :one
SELECT id, email, senha_hash, criado_em FROM users
WHERE id = $1
`

func (q *Queries) BuscarUsuarioPorID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenhaHash,
		&i.CriadoEm,
	)
	return i, err
}

const criarRefreshToken = `-- name: CriarRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expira_em)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expira_em, revogado, criado_em
`

type CriarRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiraEm  pgtype.Timestamptz `json:"expira_em"`
}

func (q *Queries) CriarRefreshToken(ctx context.Context, arg CriarRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, criarRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiraEm)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiraEm,
		&i.Revogado,
		&i.CriadoEm,
	)
	return i, err
}

const criarUsuario = `-- name: CriarUsuario :one
INSERT INTO users (email, senha_hash)
VALUES ($1, $2)
RETURNING id, email, senha_hash, criado_em
`

type CriarUsuarioParams struct {
	Email     string `json:"email"`
	SenhaHash string `json:"senha_hash"`
}

func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (User, error) {
	row := q.db.QueryRow(ctx, criarUsuario, arg.Email, arg.SenhaHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenhaHash,
		&i.CriadoEm,
	)
	return i, err
}

const revogarRefreshToken = `-- name: RevogarRefreshToken :exec
UPDATE refresh_tokens
SET revogado = TRUE
WHERE token_hash = $1
`

func (q *Queries) RevogarRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revogarRefreshToken, tokenHash)
	return err
}

const revogarTodosTokensDoUsuario = `-- name: RevogarTodosTokensDoUsuario :exec
UPDATE refresh_tokens
SET revogado = TRUE
WHERE user_id = $1 AND revogado = FALSE
`

func (q *Queries) RevogarTodosTokensDoUsuario(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revogarTodosTokensDoUsuario, userID)
	return err
}
