// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marcas.sql

package db

import (
	"context"
)

const atualizarMarca = `-- name: AtualizarMarca :one
UPDATE marcas
SET nome = $2,
    pais_origem = $3
WHERE id = $1
RETURNING id, nome, pais_origem, criado_em
`

type AtualizarMarcaParams struct {
	ID         int64  `json:"id"`
	Nome       string `json:"nome"`
	PaisOrigem string `json:"pais_origem"`
}

func (q *Queries) AtualizarMarca(ctx context.Context, arg AtualizarMarcaParams) (Marca, error) {
	row := q.db.QueryRow(ctx, atualizarMarca, arg.ID, arg.Nome, arg.PaisOrigem)
	var i Marca
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.PaisOrigem,
		&i.CriadoEm,
	)
	return i, err
}

const buscarMarca = `-- name: BuscarMarca :one
SELECT id, nome, pais_origem, criado_em FROM marcas
WHERE id = $1
`

func (q *Queries) BuscarMarca(ctx context.Context, id int64) (Marca, error) {
	row := q.db.QueryRow(ctx, buscarMarca, id)
	var i Marca
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.PaisOrigem,
		&i.CriadoEm,
	)
	return i, err
}

const criarMarca = `-- name: CriarMarca :one
INSERT INTO marcas (nome, pais_origem)
VALUES ($1, $2)
RETURNING id, nome, pais_origem, criado_em
`

type CriarMarcaParams struct {
	Nome       string `json:"nome"`
	PaisOrigem string `json:"pais_origem"`
}

func (q *Queries) CriarMarca(ctx context.Context, arg CriarMarcaParams) (Marca, error) {
	row := q.db.QueryRow(ctx, criarMarca, arg.Nome, arg.PaisOrigem)
	var i Marca
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.PaisOrigem,
		&i.CriadoEm,
	)
	return i, err
}

const deletarMarca = `-- name: DeletarMarca :exec
DELETE FROM marcas
WHERE id = $1
`

func (q *Queries) DeletarMarca(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletarMarca, id)
	return err
}

const listarMarcas = `-- name: ListarMarcas :many
SELECT id, nome, pais_origem, criado_em FROM marcas
ORDER BY nome
`

func (q *Queries) ListarMarcas(ctx context.Context) ([]Marca, error) {
	rows, err := q.db.Query(ctx, listarMarcas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Marca
	for rows.Next() {
		var i Marca
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.PaisOrigem,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
