// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Marca struct {
	ID         int64              `json:"id"`
	Nome       string             `json:"nome"`
	PaisOrigem string             `json:"pais_origem"`
	CriadoEm   pgtype.Timestamptz `json:"criado_em"`
}

type Perfume struct {
	ID       int64              `json:"id"`
	MarcaID  int64              `json:"marca_id"`
	Nome     string             `json:"nome"`
	Preco    float64            `json:"preco"`
	Tamanho  string             `json:"tamanho"`
	Genero   string             `json:"genero"`
	Estoque  int32              `json:"estoque"`
	CriadoEm pgtype.Timestamptz `json:"criado_em"`
}
