// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: perfumes.sql

package db

import (
	"context"
)

const atualizarPerfume = `-- name: AtualizarPerfume :one
UPDATE perfumes
SET marca_id = $2,
    nome = $3,
    preco = $4,
    tamanho = $5,
    genero = $6,
    estoque = $7
WHERE id = $1
RETURNING id, marca_id, nome, preco, tamanho, genero, estoque, criado_em
`

type AtualizarPerfumeParams struct {
	ID      int64   `json:"id"`
	MarcaID int64   `json:"marca_id"`
	Nome    string  `json:"nome"`
	Preco   float64 `json:"preco"`
	Tamanho string  `json:"tamanho"`
	Genero  string  `json:"genero"`
	Estoque int32   `json:"estoque"`
}

func (q *Queries) AtualizarPerfume(ctx context.Context, arg AtualizarPerfumeParams) (Perfume, error) {
	row := q.db.QueryRow(ctx, atualizarPerfume,
		arg.ID,
		arg.MarcaID,
		arg.Nome,
		arg.Preco,
		arg.Tamanho,
		arg.Genero,
		arg.Estoque,
	)
	var i Perfume
	err := row.Scan(
		&i.ID,
		&i.MarcaID,
		&i.Nome,
		&i.Preco,
		&i.Tamanho,
		&i.Genero,
		&i.Estoque,
		&i.CriadoEm,
	)
	return i, err
}

const buscarPerfume = `-- name: BuscarPerfume :one
SELECT id, marca_id, nome, preco, tamanho, genero, estoque, criado_em FROM perfumes
WHERE id = $1
`

func (q *Queries) BuscarPerfume(ctx context.Context, id int64) (Perfume, error) {
	row := q.db.QueryRow(ctx, buscarPerfume, id)
	var i Perfume
	err := row.Scan(
		&i.ID,
		&i.MarcaID,
		&i.Nome,
		&i.Preco,
		&i.Tamanho,
		&i.Genero,
		&i.Estoque,
		&i.CriadoEm,
	)
	return i, err
}

const criarPerfume = `-- name: CriarPerfume :one
INSERT INTO perfumes (marca_id, nome, preco, tamanho, genero, estoque)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, marca_id, nome, preco, tamanho, genero, estoque, criado_em
`

type CriarPerfumeParams struct {
	MarcaID int64   `json:"marca_id"`
	Nome    string  `json:"nome"`
	Preco   float64 `json:"preco"`
	Tamanho string  `json:"tamanho"`
	Genero  string  `json:"genero"`
	Estoque int32   `json:"estoque"`
}

func (q *Queries) CriarPerfume(ctx context.Context, arg CriarPerfumeParams) (Perfume, error) {
	row := q.db.QueryRow(ctx, criarPerfume,
		arg.MarcaID,
		arg.Nome,
		arg.Preco,
		arg.Tamanho,
		arg.Genero,
		arg.Estoque,
	)
	var i Perfume
	err := row.Scan(
		&i.ID,
		&i.MarcaID,
		&i.Nome,
		&i.Preco,
		&i.Tamanho,
		&i.Genero,
		&i.Estoque,
		&i.CriadoEm,
	)
	return i, err
}

const deletarPerfume = `-- name: DeletarPerfume :exec
DELETE FROM perfumes
WHERE id = $1
`

func (q *Queries) DeletarPerfume(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletarPerfume, id)
	return err
}

const listarPerfumes = `-- name: ListarPerfumes :many
SELECT id, marca_id, nome, preco, tamanho, genero, estoque, criado_em FROM perfumes
ORDER BY id
`

func (q *Queries) ListarPerfumes(ctx context.Context) ([]Perfume, error) {
	rows, err := q.db.Query(ctx, listarPerfumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perfume
	for rows.Next() {
		var i Perfume
		if err := rows.Scan(
			&i.ID,
			&i.MarcaID,
			&i.Nome,
			&i.Preco,
			&i.Tamanho,
			&i.Genero,
			&i.Estoque,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPerfumesPorMarca = `-- name: ListarPerfumesPorMarca :many
SELECT id, marca_id, nome, preco, tamanho, genero, estoque, criado_em FROM perfumes
WHERE marca_id = $1
ORDER BY id
`

func (q *Queries) ListarPerfumesPorMarca(ctx context.Context, marcaID int64) ([]Perfume, error) {
	rows, err := q.db.Query(ctx, listarPerfumesPorMarca, marcaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perfume
	for rows.Next() {
		var i Perfume
		if err := rows.Scan(
			&i.ID,
			&i.MarcaID,
			&i.Nome,
			&i.Preco,
			&i.Tamanho,
			&i.Genero,
			&i.Estoque,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
